#ifndef GLATTER_CONFIG_CHOICES_H
#define GLATTER_CONFIG_CHOICES_H

/* Platform/WSI choices (immutable) */
#define GLATTER_PLATFORM_AUTO 0
#define GLATTER_PLATFORM_WGL  1
#define GLATTER_PLATFORM_GLX  2
#define GLATTER_PLATFORM_EGL  3

#endif /* GLATTER_CONFIG_CHOICES_H */
