freebsd_instance:
  image_family: freebsd-14-2

task:
  name: "FreeBSD Build"
  install_script:
    - pkg install -y git mesa-libs pkgconf freeglut
  build_script:
    # the correct paths discovered from the debug log.
    - cc -I./include -o glgears example/glatter/glxgears.c src/glatter/glatter.c $(pkg-config --cflags --libs gl glut)