freebsd_instance:
  image_family: freebsd-14-2

task:
  name: "FreeBSD Build"
  install_script:
    - pkg install -y git mesa-libs pkgconf freeglut
  build_script:
    # Cirrus CI automatically clones the repo, so we can build directly.
    # The path to the example file is corrected here.
    - cc -I./include -o glgears example/glgears.c src/glatter.c $(pkg-config --cflags --libs gl glut)