freebsd_instance:
  image_family: freebsd-14-2

task:
  name: "FreeBSD Build"
  install_script:
    # No changes here
    - pkg install -y git mesa-libs pkgconf freeglut
  build_script:
    # Add -lX11 and -lm to the end of the command to link the required libraries
    - cc -I./include -o glgears example/glatter/glxgears.c src/glatter/glatter.c $(pkg-config --cflags --libs gl glut) -lX11 -lm