freebsd_instance:
  image_family: freebsd-14-2

task:
  name: "FreeBSD CMake Build & Test"
  install_script:
    # Add 'cmake' to the list of dependencies to install
    - pkg install -y git cmake mesa-libs pkgconf freeglut
  build_script:
    # 1. Create a build directory and configure the project using CMake
    - cmake -S . -B build

    # 2. Build the project (including all test executables)
    - cmake --build build

    # 3. Run the tests using CTest. --output-on-failure keeps logs clean
    - ctest --test-dir build --output-on-failure