/*
Copyright 2017 Ioannis Makris

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation and/or
other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

// This file was generated by glatter.py script.

#include "glatter_system_headers.h"
#include "glatter_config.h"

#include <stdio.h>
#include <inttypes.h>

#ifdef __cplusplus
extern "C" {
#endif


const char* enum_to_string_GL(GLenum e);
const char* enum_to_string_GLX(GLenum e);
const char* enum_to_string_WGL(GLenum e);
const char* enum_to_string_EGL(GLenum e);


void glatter_check_error_GL(const char* file, int line)
{
    GLenum err = glGetError();
	if (err != GL_NO_ERROR) {
		printf("GLATTER: OpenGL call produced %s error in %s(%d)\n",
			enum_to_string_GL(err), file, line);
	}
}


void* glatter_get_proc_address_GL(const char* function_name)
{
	void* ptr = (void*) wglGetProcAddress(function_name);
	if (ptr == 0)
		ptr = (void*) GetProcAddress(GetModuleHandle(TEXT("opengl32.dll")), function_name);
    return ptr;
}


void glatter_pre_callback(const char* file, int line)
{
	static __declspec(thread) DWORD thread_id;
	static int initialized = 0;
	if (!initialized) {
		thread_id = GetCurrentThreadId();
		initialized = 1;
	}
	if (GetCurrentThreadId() != thread_id) {
		printf("GLATTER: Calling OpenGL from a different thread, in %s(%d)\n", file, line);
	}
}


typedef struct
{
	char data[3*16+2];
}
Printable;


Printable get_prs(size_t sz, void* obj)
{
	Printable ret;
	ret.data[3*16+1] = 0;
	
	if (sz > 16)
        sz = 16;

	for (size_t i=0; i<sz; i++) {
		snprintf(&ret.data[i*3], sizeof(ret)-3*i-1," %02x", (unsigned char) *(((char*)obj)+i) );
	}
	
	ret.data[0] = '[';
	ret.data[3*sz] = ']';

	return ret;
}


#ifndef GLATTER_LOG
#define printf
#endif


#define GLATTER_FBLOCK(return_or_not, family, cder, rtype, cconv, name, cargs, dargs)\
    cder rtype cconv name dargs;\
    typedef rtype (cconv *glatter_##name##_t) dargs;\
    extern glatter_##name##_t glatter_##name##_ptr;\
	extern rtype cconv glatter_##name##_init dargs;\
	rtype cconv glatter_##name##_init dargs\
	{\
		glatter_##name##_ptr = (glatter_##name##_t) glatter_get_proc_address_##family(#name);\
		return_or_not glatter_##name##_ptr cargs;\
	}\
	glatter_##name##_t glatter_##name##_ptr = glatter_##name##_init;


#define GLATTER_DBLOCK(file, line, name, printf_fmt, ...) \
    glatter_pre_callback(file, line);\
	printf("GLATTER: calling in '%s'(%d):\n", file, line);\
	printf("GLATTER: " #name #printf_fmt "%s", __VA_ARGS__);


#define GET_PRS(v)\
    (get_prs(sizeof(v), (void*)(&(v))).data)


#if defined(__llvm__) || defined (__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-value"
#endif

#include "glatter.c_gen"

#if defined(__llvm__) || defined (__clang__)
#pragma clang diagnostic pop
#endif


#ifdef __cplusplus
}
#endif
